# Generated by Django 4.2.8 on 2023-12-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_tag_task_due_date_task_status_alter_task_taskdesc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(to='home.tag'),
        ),
    ]
